### ISSUE TITLE
使用ubuntu安装时发生错误

### ISSUE THREAD

**Issue by evertears** [honmaple/maple-blog#10]
Rolling back uninstall of cffi
  Moving to /home/tom/anaconda3/lib/python3.7/site-packages/_cffi_backend.cpython-37m-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-3auvpro_/_cffi_backend.cpython-37m-x86_64-linux-gnu.so
  Moving to /home/tom/anaconda3/lib/python3.7/site-packages/cffi-1.12.2.dist-info/
   from /home/tom/anaconda3/lib/python3.7/site-packages/~ffi-1.12.2.dist-info
  Moving to /home/tom/anaconda3/lib/python3.7/site-packages/cffi/
   from /home/tom/anaconda3/lib/python3.7/site-packages/~ffi
Command "/home/tom/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zbhm6q3u/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rnz0l8ky/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-zbhm6q3u/cffi/

**Comment by honmaple** [comment]
单独安装**cffi**是什么现象，如果还是有问题，可以尝试`apt-get install libffi-dev`

**Comment by evertears** [comment]
`python runserver.py db init
Usage: runserver.py [OPTIONS] COMMAND [ARGS]...
Try "runserver.py --help" for help.

Error: No such command "db".
`

这个是什么原因呢？

**Comment by honmaple** [comment]
db命令由`flask_migrate`提供，`pip install flask_migrate`即可

**Comment by evertears** [comment]
`(base) tom@ubuntu:~/maple-blog$ python runserver.py db initdb
Traceback (most recent call last):
  File "runserver.py", line 32, in <module>
    app = create_app('config')
  File "/home/tom/maple-blog/maple/__init__.py", line 25, in create_app
    extension.init_app(app)
  File "/home/tom/maple-blog/maple/extension/__init__.py", line 36, in init_app
    maple.init_app(app)
  File "/home/tom/maple-blog/maple/extension/maple.py", line 34, in init_app
    Logging(app)
  File "/home/tom/anaconda3/lib/python3.7/site-packages/flask_maple/log.py", line 50, in __init__
    self.init_app(app)
  File "/home/tom/anaconda3/lib/python3.7/site-packages/flask_maple/log.py", line 57, in init_app
    config['info'], maxBytes=100000, backupCount=10)
  File "/home/tom/anaconda3/lib/python3.7/logging/handlers.py", line 147, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/tom/anaconda3/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/tom/anaconda3/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/tom/anaconda3/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tom/maple-blog/logs/info.log'`

**Comment by evertears** [comment]
安装`flask_migrate`之后仍会报错，如果把`$ python runserver.py db initdb`改成`$ python runserver.py  initdb`则可以运行，不知道这样有什么影响吗？

**Comment by honmaple** [comment]
`python runserver.py initdb`和`python runserver.py db initdb`都可以初始化数据库，使用`flask_migrate`是为了方便后续升级修改数据库，不用的话只能手动修改，可使用`python runserver.py db --help`查看相关命令

**Comment by evertears** [comment]
好的明白了，谢谢你啦，非常感谢！！
