### ISSUE TITLE
there is a error message when i run python manager.py db init

### ISSUE THREAD

**Issue by li7228166** [honmaple/maple-blog#2]
Hello(您好)

I had download  flask-maple from github ,and i had run  'python setup.py install ' in flask-maple directory and ....but,   when i run 'python manager.py db init' ,there is a error message 

Traceback (most recent call last):
  File "manager.py", line 12, in <module>
    from maple import create_app
  File "/Users/tjrb/maple-blog/maple/__init__.py", line 12, in <module>
    from .extensions import register_maple
  File "/Users/tjrb/maple-blog/maple/extensions.py", line 17, in <module>
    from flask_maple.mail import MapleMail
ImportError: cannot import name 'MapleMail'

@honmaple

**Comment by honmaple** [comment]
Sorry,now you can use `git pull` again,I have uploaded newest code to github.
But sending mail maybe not work,I will check it tonight.

**Comment by hareteam** [comment]
@honmaple  dear friend:
I saw the message ..... and i want rebuild maple-blog


```
pip install Flask
git clone https://github.com/honmaple/flask-maple
cd flask-maple 
python setup.py install

git clone https://github.com/honmaple/maple-blog
cd maple-blog
vim requirements.txt
 change SQLAlchemy version to 2.2
pip install -r ./requirements.txt
pip install flask_migrate
mv config.example config 
```

and there a error message 

```
Traceback (most recent call last):
  File "manager.py", line 12, in <module>
    from maple import create_app
  File "/Users/olddog/maple-blog/maple/__init__.py", line 15, in <module>
    from .urls import register_routes
  File "/Users/olddog/maple-blog/maple/urls.py", line 14, in <module>
    from maple.user.urls import site as user_site
  File "/Users/olddog/maple-blog/maple/user/urls.py", line 14, in <module>
    from .views import (UserInforView, UserPasswordView, UserBlogListView,
  File "/Users/olddog/maple-blog/maple/user/views.py", line 17, in <module>
    from flask_maple.form import flash_errors
ModuleNotFoundError: No module named 'flask_maple.form'
```

**Comment by honmaple** [comment]
@hareteam flask-maple isn't newest,`git pull` again and it will work well.
