### ISSUE TITLE
new version of maple-blog has some Defect

### ISSUE THREAD

**Issue by hareteam** [honmaple/maple-blog#3]
Today i re pull the code from github,
but when i init maple db ,system return message is:

```
(py36) bogon:maple-blog dog$ python manager.py db init
Traceback (most recent call last):
  File "manager.py", line 12, in <module>
    from maple import create_app
  File "/Users/dog/maple-blog/maple/__init__.py", line 15, in <module>
    from .urls import register_routes
  File "/Users/dog/maple-blog/maple/urls.py", line 15, in <module>
    from maple.blog.urls import site as blog_site
  File "/Users/dog/maple-blog/maple/blog/urls.py", line 14, in <module>
    from .views import (BlogListView, BlogView, BlogRssView, BlogArchiveView,
  File "/Users/dog/maple-blog/maple/blog/views.py", line 21, in <module>
    from .filters import safe_markdown
  File "/Users/olddog/maple-blog/maple/blog/filters.py", line 18, in <module>
    from fortune import fortune
  File "/Users/olddog/.virtualenvs/py36/lib/python3.6/site-packages/fortune/__init__.py", line 183
    raise ValueError, 'Can\'t find file "%s"' % fortune_index_file
                    ^
SyntaxError: invalid syntax
```

**Comment by hareteam** [comment]
And i re pull flask_maple, i found there some update......
so.....
i git pull and python setup.py install

but when i init maple db , the return message is:


```
(py36) bogon:maple-blog olddog$ python manager.py db init
Traceback (most recent call last):
  File "manager.py", line 12, in <module>
    from maple import create_app
  File "/Users/olddog/maple-blog/maple/__init__.py", line 15, in <module>
    from .urls import register_routes
  File "/Users/olddog/maple-blog/maple/urls.py", line 15, in <module>
    from maple.blog.urls import site as blog_site
  File "/Users/olddog/maple-blog/maple/blog/urls.py", line 14, in <module>
    from .views import (BlogListView, BlogView, BlogRssView, BlogArchiveView,
  File "/Users/olddog/maple-blog/maple/blog/views.py", line 21, in <module>
    from .filters import safe_markdown
  File "/Users/olddog/maple-blog/maple/blog/filters.py", line 18, in <module>
    from fortune import fortune
  File "/Users/olddog/.virtualenvs/py36/lib/python3.6/site-packages/fortune/__init__.py", line 183
    raise ValueError, 'Can\'t find file "%s"' % fortune_index_file
                    ^
SyntaxError: invalid syntax
```

**Comment by honmaple** [comment]
You shouldn't use `pip install fortune`.
The right way is 
```
git clone https://github.com/honmaple/fortune
ln -s path/fortune/fortune blog_path/fortune
```

Or if you don't want to use fortune,just find file 
**temaplates/blog/panel.html** and delete the No.11 line **{{ random_fortune() }}**.
**maple/blog/filters.py** and remove fortune function.

**Comment by li7228166** [comment]
@honmaple   i tried it , but i found:

```
Traceback (most recent call last):
  File "manager.py", line 12, in <module>
    from maple import create_app
  File "/home/dogdog/maple-blog/maple/__init__.py", line 15, in <module>
    from .urls import register_routes
  File "/home/dogdog/maple-blog/maple/urls.py", line 15, in <module>
    from maple.blog.urls import site as blog_site
  File "/home/dogdog/maple-blog/maple/blog/urls.py", line 14, in <module>
    from .views import (BlogListView, BlogView, BlogRssView, BlogArchiveView,
  File "/home/dogdog/maple-blog/maple/blog/views.py", line 21, in <module>
    from .filters import safe_markdown
  File "/home/dogdog/maple-blog/maple/blog/filters.py", line 20, in <module>
    from org import org_to_html
ModuleNotFoundError: No module named 'org'

```

**Comment by honmaple** [comment]
see [https://github.com/honmaple/maple-blog/issues/1](https://github.com/honmaple/maple-blog/issues/1)
```
git clone https://github.com/honmaple/org-python
ln -s path/org-python/org.py blog_path/org.py
```
I have updated **readme**
